using Walker.Core;
using Walker.Execution;
using Walker.Git;
using Walker.Roslyn;
using Xunit;
namespace Walker.Tests;

public sealed class RobustnessTests
{
    [Fact]
    public async Task RenamedFileOnlyAuthorizesActuallyChangedLines()
    {
        using var workspace = new Workspace();
        var runner = await Repository(workspace);
        workspace.Write("src/Code.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        workspace.Write("src/Old.cs", "class C {\n bool M(int a, int b) => a > b;\n bool N(int a) => a > 1;\n}\n");
        await Git(runner, workspace, "add", "."); await Git(runner, workspace, "commit", "-m", "base");
        await Git(runner, workspace, "mv", "src/Old.cs", "src/New.cs");
        workspace.Write("src/New.cs", "class C {\n bool M(int a, int b) => a > b;\n bool N(int a) => a > 2;\n}\n");
        await Git(runner, workspace, "add", "."); await Git(runner, workspace, "commit", "-m", "rename");
        var change = Assert.Single(await new GitChangeProvider(runner).GetChangesAsync(new(workspace.Root, "HEAD~1", "src/Code.csproj", ["Tests.csproj"]), default));
        Assert.Equal("src/New.cs", change.File);
        Assert.Equal([new LineRange(3, 3)], change.Lines);
    }
    [Fact]
    public async Task ParsesUnusualPathsAndSkipsOnlyGeneratedHeaders()
    {
        using var workspace = new Workspace();
        var runner = await Repository(workspace);
        workspace.Write("src/Code.csproj", "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        var files = new[] { "src/With Space.cs", "src/Ünïcode.cs", "src/Quote\"d.cs", "src/Header.cs", "src/Body.cs" };
        foreach (var file in files) workspace.Write(file, "class C {}\n");
        await Git(runner, workspace, "add", "."); await Git(runner, workspace, "commit", "-m", "base");
        foreach (var file in files.Take(3)) workspace.Write(file, "class C { bool M() => true; }\n");
        workspace.Write("src/Header.cs", "// <auto-generated/>\nclass C { bool M() => true; }\n");
        workspace.Write("src/Body.cs", "class C { string M() => \"<auto-generated\"; }\n");
        var changes = await new GitChangeProvider(runner).GetChangesAsync(new(workspace.Root, "HEAD", "src/Code.csproj", ["Tests.csproj"]), default);
        Assert.Equal(new[] { "src/Body.cs", "src/Quote\"d.cs", "src/With Space.cs", "src/Ünïcode.cs" }.Order(StringComparer.Ordinal), changes.Select(c => c.File));
        Assert.All(changes, c => Assert.True(c.HasUncommittedChanges));
    }
    [Fact]
    public async Task HungMutantIsDetectedRestoredAndDoesNotStopTheRun()
    {
        using var workspace = new Workspace();
        workspace.Write("Code.cs", "class C { bool M(int a, int b) => a >= b; }");
        var path = Path.Combine(workspace.Root, "Code.cs");
        var bytes = File.ReadAllBytes(path);
        var baseline = true;
        var executor = new DotnetMutationExecutor(new AsyncRunner(async (request, token) =>
        {
            if (request.Arguments[0] != "test") return new(0, "", "", 1);
            if (!baseline) await Task.Delay(Timeout.Infinite, token);
            WriteReport(request, failed: 0);
            return new(0, "", "", 1);
        }), hangAllowance: TimeSpan.FromMilliseconds(200));
        var request = new VerificationRequest(workspace.Root, "HEAD~1", "Code.csproj", ["Tests.csproj"]);
        await executor.VerifyAsync(request, default);
        baseline = false;
        var candidate = Assert.Single((await new RoslynMutationDiscoverer().DiscoverAsync(workspace.Root, [new("Code.cs", [new(1, 1)], false)], default)).Mutants);
        var result = await executor.ExecuteAsync(candidate, new(request, new AllTestsSelector(request.Tests)), default);
        Assert.Equal(MutationOutcome.Hung, result.Outcome);
        Assert.Equal(bytes, File.ReadAllBytes(path));
        Assert.False(File.Exists(MutationJournal.PathFor(workspace.Root)));

        var executed = new List<string>();
        var fake = new FakeEngine([DiscoveryTests.Dummy("a"), DiscoveryTests.Dummy("b")], m =>
        {
            executed.Add(m.Id);
            return new(m, m.Id == "a" ? MutationOutcome.Hung : MutationOutcome.Killed);
        });
        var verification = await new VerificationEngine(fake, fake, fake, fake).VerifyAsync(request);
        Assert.Equal(["a", "b"], executed);
        Assert.Equal("passed", verification.Status);
        Assert.Equal(1, verification.Hung);
    }
    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task JournalRepairsInterruptedMutationButNeverOverwritesLaterEdits(bool editedAfterCrash)
    {
        using var workspace = new Workspace();
        workspace.Write("Code.cs", "class C { bool M(int a, int b) => a >= b; }");
        var path = Path.Combine(workspace.Root, "Code.cs");
        var original = File.ReadAllBytes(path);
        string? journal = null; byte[]? mutated = null;
        var runner = new FakeRunner(request =>
        {
            // Capture the on-disk state at the moment a crash would leave it.
            journal = File.ReadAllText(MutationJournal.PathFor(workspace.Root));
            mutated = File.ReadAllBytes(path);
            return new(1, "compile error", "", 1);
        });
        var request = new VerificationRequest(workspace.Root, "HEAD~1", "Code.csproj", ["Tests.csproj"]);
        var candidate = Assert.Single((await new RoslynMutationDiscoverer().DiscoverAsync(workspace.Root, [new("Code.cs", [new(1, 1)], false)], default)).Mutants);
        await new DotnetMutationExecutor(runner).ExecuteAsync(candidate, new(request, new AllTestsSelector(request.Tests)), default);
        Assert.Null(await MutationJournal.RecoverAsync(workspace.Root, default));
        File.WriteAllText(MutationJournal.PathFor(workspace.Root), journal);
        File.WriteAllBytes(path, mutated!);
        if (editedAfterCrash)
        {
            File.WriteAllText(path, "// user edit\n");
            await Assert.ThrowsAsync<InvalidOperationException>(() => MutationJournal.RecoverAsync(workspace.Root, default));
            Assert.Equal("// user edit\n", File.ReadAllText(path));
            File.Delete(MutationJournal.PathFor(workspace.Root));
            return;
        }
        Assert.NotNull(await MutationJournal.RecoverAsync(workspace.Root, default));
        Assert.Equal(original, File.ReadAllBytes(path));
        Assert.False(File.Exists(MutationJournal.PathFor(workspace.Root)));
    }
    [Fact]
    public async Task ArithmeticResolvesTypesFromOtherProjectFilesAndCountsUnresolved()
    {
        using var workspace = new Workspace();
        workspace.Write("Rates.cs", "using System.Collections.Generic; public partial class Rates { public decimal Fee = 2m; public List<int> Items = new(); }");
        workspace.Write("Code.cs", "public partial class Rates { decimal Total(decimal x) => x * Fee; int Count() => Items.Count + 1; int Unknown() => Missing.Value + 1; }");
        var change = new SourceChange("Code.cs", [new(1, 1)], false);
        var isolated = await new RoslynMutationDiscoverer().DiscoverAsync(workspace.Root, [change], default);
        Assert.Empty(isolated.Mutants);
        Assert.Equal(3, isolated.UnresolvedArithmetic);
        var context = new[] { Path.Combine(workspace.Root, "Rates.cs"), Path.Combine(workspace.Root, "Code.cs") };
        var found = await new RoslynMutationDiscoverer(_ => Task.FromResult<IEnumerable<string>>(context)).DiscoverAsync(workspace.Root, [change], default);
        Assert.Equal(["Rates.Total", "Rates.Count"], found.Mutants.Select(m => m.Member));
        Assert.Equal(1, found.UnresolvedArithmetic);
    }
    [Fact]
    public void SelectionRotatesAcrossFilesAndOperators()
    {
        static Walker.Core.Mutant At(string id, string file, MutationOperator op, int line) => DiscoveryTests.Dummy(id, op) with { File = file, Line = line, SpanStart = line };
        var dense = Enumerable.Range(1, 5).Select(i => At("a" + i, "A.cs", MutationOperator.ConditionalBoundary, i));
        var selected = VerificationEngine.Select([.. dense, At("b", "B.cs", MutationOperator.ConditionalBoundary, 1), At("c", "A.cs", MutationOperator.Equality, 9)], 3);
        Assert.Equal(["a1", "b", "c"], selected.Select(m => m.Id));
    }
    [Fact]
    public async Task OutputLimitKeepsExactTail()
    {
        if (OperatingSystem.IsWindows()) return;
        var result = await new ProcessRunner().RunAsync(new("bash", ["-c", "seq 1 20000"], Path.GetTempPath(), OutputLimit: 100), default);
        Assert.True(result.OutputTruncated);
        var expected = string.Concat(Enumerable.Range(1, 20000).Select(i => i + "\n"));
        Assert.Equal(expected[^100..], result.StandardOutput);
    }
    private static void WriteReport(ProcessRequest request, int failed)
    {
        var directory = request.Arguments[request.Arguments.ToList().IndexOf("--results-directory") + 1];
        File.WriteAllText(Path.Combine(directory, "tests.trx"), $"<TestRun><ResultSummary><Counters executed='1' passed='{1 - failed}' failed='{failed}' /></ResultSummary></TestRun>");
    }
    private static async Task<ProcessRunner> Repository(Workspace workspace)
    {
        var runner = new ProcessRunner();
        await Git(runner, workspace, "init"); await Git(runner, workspace, "config", "user.email", "tests@example.invalid");
        await Git(runner, workspace, "config", "user.name", "Tests");
        return runner;
    }
    private static async Task Git(ProcessRunner runner, Workspace workspace, params string[] args)
    {
        var result = await runner.RunAsync(new("git", args, workspace.Root), default);
        Assert.True(result.ExitCode == 0, result.StandardError);
    }
}
internal sealed class AsyncRunner(Func<ProcessRequest, CancellationToken, Task<ProcessResult>> run) : IProcessRunner
{
    public Task<ProcessResult> RunAsync(ProcessRequest request, CancellationToken cancellationToken) => run(request, cancellationToken);
}
