<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup></PropertyGroup><ItemGroup><ProjectReference Include="../Walker.Core/Walker.Core.csproj" /><ProjectReference Include="../Walker.BuildLogger/Walker.BuildLogger.csproj" /><ProjectReference Include="../Walker.Roslyn/Walker.Roslyn.csproj" /><ProjectReference Include="../Walker.CoverageCollector/Walker.CoverageCollector.csproj" /></ItemGroup></Project>
