using System.Text.RegularExpressions;
using Walker.Core;
namespace Walker.Git;
public sealed partial class GitChangeProvider(IProcessRunner runner, IProductionSourceScope? sourceScope = null) : IChangeProvider
{
    public async Task<IReadOnlyList<SourceChange>> GetChangesAsync(VerificationRequest request, CancellationToken cancellationToken)
    {
        async Task<string> Git(params string[] args)
        {
            var result = await runner.RunAsync(new("git", args, request.Root, OutputLimit: 16 * 1024 * 1024), cancellationToken);
            if (result.OutputTruncated) throw new InvalidOperationException("Git output exceeds the safety limit; narrow the change.");
            if (result.ExitCode != 0) throw new InvalidOperationException("Git discovery failed: " + result.StandardError.Trim());
            return result.StandardOutput;
        }
        // Three-dot semantics use the merge base; compare that commit to the actual working copy.
        var baseCommit = (await Git("rev-parse", "--verify", "--end-of-options", request.Base + "^{commit}")).Trim();
        var mergeBase = (await Git("merge-base", baseCommit, "HEAD")).Trim();
        var names = (await Git("diff", "--name-only", "-z", "--diff-filter=AMR", mergeBase, "--", "*.cs")).Split('\0', StringSplitOptions.RemoveEmptyEntries);
        var excludes = (request.Exclude ?? []).Select(pattern => new Regex("^" + Regex.Escape(pattern.Replace('\\', '/'))
            .Replace(@"\*\*/", "(?:.*/)?").Replace(@"\*\*", ".*").Replace(@"\*", "[^/]*").Replace(@"\?", "[^/]") + "$",
            RegexOptions.CultureInvariant | RegexOptions.NonBacktracking)).ToArray();
        names = names.Where(file => !Ignore(file, excludes)).ToArray();
        if (names.Length == 0) return [];
        var dirty = (await Git("diff", "--name-only", "-z", "HEAD", "--", "*.cs")).Split('\0').ToHashSet(StringComparer.Ordinal);
        var testDirectories = new Dictionary<string, bool>(StringComparer.Ordinal);
        var result = new List<SourceChange>();
        var compiledFiles = sourceScope == null ? null : await sourceScope.GetFilesAsync(request, cancellationToken);
        var projectDirectory = Path.GetDirectoryName(Path.GetFullPath(request.Project, request.Root))!;
        foreach (var file in names.Order(StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();
            var fullPath = Path.GetFullPath(file, request.Root);
            if (compiledFiles != null ? !compiledFiles.Contains(fullPath) : !fullPath.StartsWith(projectDirectory + Path.DirectorySeparatorChar, StringComparison.Ordinal)) continue;
            if (IsTestSource(Path.GetDirectoryName(fullPath)!, request.Root, testDirectories)) continue;
            var content = await File.ReadAllTextAsync(fullPath, cancellationToken);
            if (content.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) continue;
            var diff = await Git("diff", "--no-ext-diff", "--no-textconv", "--unified=0", mergeBase, "--", file);
            var lines = new List<LineRange>();
            foreach (Match match in Hunk().Matches(diff))
            {
                var start = int.Parse(match.Groups[1].Value);
                var count = match.Groups[2].Success ? int.Parse(match.Groups[2].Value) : 1;
                // Deleted lines do not authorize mutating unchanged neighbours.
                if (count > 0) lines.Add(new(start, start + count - 1));
            }
            if (lines.Count > 0) result.Add(new(file.Replace('\\', '/'), lines, dirty.Contains(file)));
        }
        return result;
    }
    private static bool IsTestSource(string directory, string root, Dictionary<string, bool> cache)
    {
        if (cache.TryGetValue(directory, out var result)) return result;
        var projects = Directory.GetFiles(directory, "*.csproj");
        if (projects.Length > 0)
        {
            result = projects.Any(project =>
            {
                var text = File.ReadAllText(project);
                return text.Contains("<IsTestProject>true", StringComparison.OrdinalIgnoreCase)
                    || text.Contains("Microsoft.NET.Test.Sdk", StringComparison.OrdinalIgnoreCase);
            });
        }
        else if (directory != root && Directory.GetParent(directory) is { } parent && parent.FullName.StartsWith(root, StringComparison.Ordinal))
            result = IsTestSource(parent.FullName, root, cache);
        cache[directory] = result;
        return result;
    }
    private static bool Ignore(string file, IReadOnlyList<Regex> excludes)
    {
        var segments = file.Split('/');
        if (segments.Any(s => s.Equals("bin", StringComparison.OrdinalIgnoreCase) || s.Equals("obj", StringComparison.OrdinalIgnoreCase)
            || s.Equals("Generated", StringComparison.OrdinalIgnoreCase) || s.Equals("tests", StringComparison.OrdinalIgnoreCase))) return true;
        if (file.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase) || file.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || file.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase) || file.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)) return true;
        return excludes.Any(pattern => pattern.IsMatch(file));
    }
    [GeneratedRegex(@"^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@", RegexOptions.Multiline)]
    private static partial Regex Hunk();
}
